 const cartActionTypes={
     TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
 ADD_ITEM: 'ADD_ITEM',
 REMOVE_ITEM_FROM_CART:'REMOVE_ITEM_FROM_CART',
 REDUCE_ITEM_BY_ONE: 'REDUCE_ITEM_BY_ONE',
 ADD_ONE_OR_MORE_OF_AN_ITEM: 'ADD_ONE_OR_MORE_OF_AN_ITEM',
 CLEAR_CART: 'CLEAR_CART'
}

export default cartActionTypes