const reviewActionTypes = {
    FETCH_REVIEWS_START: "FETCH_REVIEWS_START",
    FETCH_REVIEWS_FAILURE: "FETCH_REVIEWS_FAILURE",
    FETCH_REVIEWS_SUCCESS: "FETCH_REVIEWS_SUCCESS",
    ADD_REVIEW_START: "ADD_REVIEW_START",
    ADD_REVIEW_SUCCESS: "ADD_REVIEW_SUCCESS",
    ADD_REVIEW_FAILURE: "ADD_REVIEW_FAILURE",
    USER_VERIFIED: 'USER_VERIFIED'
}
export default reviewActionTypes