const reviewActionTypes = {
    FETCH_REVIEWS_START: "FETCH_REVIEWS_START",
    FETCH_REVIEWS_FAILURE: "FETCH_REVIEWS_FAILURE",
    FETCH_REVIEWS_SUCCESS: "FETCH_REVIEWS_SUCCESS",
    ADD_REVIEW_START: "ADD_REVIEW_START",
    ADD_REVIEW_SUCCESS: "ADD_REVIEW_SUCCESS",
    ADD_REVIEW_FAILURE: "ADD_REVIEW_FAILURE",
    USER_VERIFIED: 'USER_VERIFIED',
    FETCH_ALLREVIEWS_START: "FETCH_ALLREVIEWS_START",
    FETCH_ALLREVIEWS_FAILURE: "FETCH_ALLREVIEWS_FAILURE",
    FETCH_ALLREVIEWS_SUCCESS: "FETCH_ALLREVIEWS_SUCCESS"
}
export default reviewActionTypes