const blogActionTypes = {
    ADD_POST_START: 'ADD_POST_START',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
    ADD_POST_FAILURE: 'ADD_POST_FAILURE',
    EDIT_POST_START: 'EDIT_POST_START',
    EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
    EDIT_POST_FAILURE: 'EDIT_POST_FAILURE',
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE'
}

export default blogActionTypes