const adminActionTypes = {
    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_FAILURE : 'ADD_PRODUCT_FAILURE',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    EDIT_PRODUCT_START : 'EDIT_PRODUCT_START',
    EDIT_PRODUCT_FAILURE : 'EDIT_PRODUCT_FAILURE',
    EDIT_PRODUCT_SUCCESS : 'EDIT_PRODUCT_SUCCESS',

}
export default adminActionTypes