const adminActionTypes = {
    ADD_PRODUCT_START: 'ADD_PRODUCT_START',
    ADD_PRODUCT_FAILURE : 'ADD_PRODUCT_FAILURE',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    EDIT_PRODUCT_START : 'EDIT_PRODUCT_START',
    EDIT_PRODUCT_FAILURE : 'EDIT_PRODUCT_FAILURE',
    EDIT_PRODUCT_SUCCESS : 'EDIT_PRODUCT_SUCCESS',
    NEW_PAGE_START:'NEW_PAGE_START',
    NEW_PAGE_SUCCESS:'NEW_PAGE_SUCCESS',
    NEW_PAGE_FAILURE:'NEW_PAGE_FAILURE'
}
export default adminActionTypes