const orderActionTypes = {
    NEW_ORDER_START: "NEW_ORDER_START",
    NEW_ORDER_SUCCESS: "NEW_ORDER_SUCCESS",
    NEW_ORDER_FAILURE: "NEW_ORDER_FAILURE",
    FETCH_ORDERS_START: "FETCH_ORDERS_START",
    FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    ADD_ORDER_TO_USER: "ADD_ORDER_TO_USER"
}
export default orderActionTypes